### ISSUE TITLE
Allow local clients to ignore upstream parameter and continue as normal

### ISSUE THREAD

**Issue by Adrian-at-CrimsonAzure** [freman/caddy-reauth#14]
I like using my domain for shorthand within my network (plex.[domain].com) rather than type out IPs when configuring clients that interconnect so that changes in address structure don't break configurations.

Is there a way to allow a client to access the proxy even if the upstream check fails?

    sonarr.domain.com:443 {
            reauth {
                    path /
                    ignore localclients #or something
                    failure redirect target=https://organizr.domain.com/
                    upstream url=https://organizr.domain.com/auth.php?user,cookies=true
            }
            proxy / 10.0.0.110 { transparent websocket }
    }

**Comment by freman** [comment]
I might just be tired, but it sounds like you want it to "accept" if upstream is unreachable?
Or do you want a whitelist you can give cidrs to?

**Comment by Adrian-at-CrimsonAzure** [comment]
I have actually completely forgotten what I was trying to request. Whatever it was it must not have been that important I guess...

**Comment by freman** [comment]
Sorry it took so long to get back to you, if you remember or it crops up again, please feel free to nag me
