### ISSUE TITLE
Build error (bigcache)

### ISSUE THREAD

**Issue by TheOneValen** [freman/caddy-reauth#25]
Hi

It seems that I cannot build caddy-reauth anymore due to the following error:

`freman/caddy-reauth/backends/refresh/auth.go:393:23: undefined: bigcache.EntryNotFoundError`

Did some dependency change?

Greetings,
Valen

**Comment by freman** [comment]
Big cache is a big pain in the arse, when I get back from holiday I'll remove it and refactor the code around it. Sorry about that

**Comment by freman** [comment]
Everything builds, release 1.0.14 is now available in caddy
