### ISSUE TITLE
Document use of spaces in LDAP parameters

### ISSUE THREAD

**Issue by mh720** [freman/caddy-reauth#28]
Recently needed to filter using an LDAP OU= with a space in it. After some trial-and-error, it looks like c/c++/java escaping works here: OU=GROUP\u0020NAME

Please consider adding to the README if this is expected and/or supported.

**Comment by freman** [comment]
Nice find, I believe you're the first person who's tried to use spaces that I know of, we've not had to here so it's never come up. I'll absolutely update the documentation to reflect this possibility.
