### ISSUE TITLE
Distributed plugin version does not match website version

### ISSUE THREAD

**Issue by joshuata** [freman/caddy-reauth#3]
The version of the plugin available through the [download sites](https://caddyserver.com/docs/http.reauth) was updated 29 Jun 2017, where version 1.0.4 was released 10 Jul 2017.

**Comment by freman** [comment]
The version of the plugin on the download sites is the same as this one. That 'last updated' is for the documentation. Which hasn't really changed much, but I went and clicked 'edit/save' on for you

**Comment by joshuata** [comment]
Thank you so much for doing that even though it wasn't needed! 

I was assuming the changes hasn't been pushed since I tried adding multiple locations as added in 1.0.3, but caddy would immediately crash during startup. I guess I will have to try other fixes...

**Comment by freman** [comment]
What's the crash?

Probably a bug I have created :D

**Comment by joshuata** [comment]
I'm not sure. I can't get any logs from the crash, it just doesn't start. If I comment out the reauth block it works, so my guess would be in the parsing code. 

I'll try and get more info tomorrow and let you know.

**Comment by freman** [comment]
Can you share a sample of your non-working config?

**Comment by joshuata** [comment]
Never mind. I hadn't restarted the jail, so it hadn't replaced the old version.
