### ISSUE TITLE
LDAP?

### ISSUE THREAD

**Issue by jcgruenhage** [freman/caddy-reauth#4]
Would it maybe be possible to authenticate against an LDAP source?

**Comment by freman** [comment]
Hi, Sorry it's taken so long to get back to this, every time I've opened it something has come up.

I haven't been ignoring you but I'm about to go on holiday so the next time I'll have a chance to look will be next year.

I am open to discussion about the best way to do this tho as every ldap setup I've ever been around has been different (and usually ended up needing specific patching)

**Comment by jcgruenhage** [comment]
No problem, have a nice holiday :)

**Comment by freman** [comment]
tgulacsi was kind enough to [add this feature](https://github.com/freman/caddy-reauth/pull/7) before I got to it
